language: generic
os:
  - linux
notifications:
  email: false
  slack:
    secure: 4RATxrsRKGn0ToUxGb4WBYHCAKzJAdXPJURgEscdcpZxNUxKjtUJwMvtSO5aEC8xROICyHUyj3YLLB5gzkNhrRmNidbvYjeSU653y+etqMRMGkAttVL152JHZWPd93VM8cMVUJ85Xl4d42NwHv5RB6tOAEZVNP3XS6tE6+JN88Kc9PiHF6Sjdlwhb/v4ABtaPp6mbOPIGmowXz0jc/8mo2wLIf9rn7El57n+g5IR7vTM63jJ75StRz7K4cxb842P1WNrS5Kuhzxvxpi63XdbwOnV/UVP+tGONutfWWbX+MtNyWdupRKVBP43zpKLoLeCNs9BYnRqBNR88LILEqDth7cJgM+1jDOb0PyDI0D8wuOWDTuqan7SL1rnpqOveE97F+5/tAB9FX5dskLT+RM31prKNJ0VcY7o//Aks5Nw47Me2nygTcaeHXpkBIlq0WyeVqEu4Fmqd6oB4xHl25PNnaeJhtqeuSKHH6c50LVd+xBN7AwknFyQkq2lm771t3vcghOFQOyc8/CKcdZ6DjaLglew7u4vQEyEW45/zPx5QIs5aSDbPdwEZgwCgd2GtivEzSECXTPzNaJvVeoodPcIjCqA/PkJCJ5rCSfY+u0Y9t3i/Wdzge8px7ZLGo/9T7n0/cycarsPGoUd5KmEyQs9r1GyL9ic/c7p/EZ2kEnUFqo=
env:
  global:
  - SKLLVERSION="2.0"
  - TESTDIR="${HOME}/skllcode/tests"
  matrix:
  - TESTFILES="tests/test_featureset.py tests/test_utilities.py"
  - TESTFILES="tests/test_output.py"
  - TESTFILES="tests/test_regression.py"
  - TESTFILES="tests/test_input.py tests/test_preprocessing.py tests/test_metrics.py tests/test_custom_learner.py tests/test_logutils.py tests/test_examples.py"
  - TESTFILES="tests/test_classification.py tests/test_cv.py tests/test_ablation.py"

# run on the new Travis infrastructure
sudo: false

# set up conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
before_install:
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH="${HOME}/miniconda3/bin:$PATH"
# clone just the SKLL tests and examples and install the SKLL package
install:
  - mkdir ${HOME}/skllcode
  - cd ${HOME}/skllcode
  - git init
  - git remote add -f origin https://github.com/EducationalTestingService/skll.git
  - git config core.sparsecheckout true
  - echo "tests/*" > .git/info/sparse-checkout
  - echo "examples/*" > .git/info/sparse-checkout
  - git pull --depth=1 origin master
  - conda create --name skllenv python=3.6 --yes
  - ${HOME}/miniconda3/envs/skllenv/bin/pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple skll==${SKLLVERSION}

# Run tests using the installed SKLL package
script:
  - ${HOME}/miniconda3/envs/skllenv/bin/nosetests --nologcapture -w ${TESTDIR} ${TESTFILES}
